### ISSUE TITLE
Make search bar more noticeable

### ISSUE THREAD

**Issue by platers** [platers/MAL-Map#11]
Some people never notice the sidebar. Maybe add a search icon or different colored background?

**Comment by ramanathanMuthuraman** [comment]
@platers: Have created a PR to update  the sidebar and search input styling to provide more visibility. Please check it out - https://github.com/platers/MAL-Map/pull/29

**Comment by ramanathanMuthuraman** [comment]
@platers : Have fixed the conflicts and updated the styles, please review the same.
