### ISSUE TITLE
Advanced Clustering: Centrality and Node Roles

### ISSUE THREAD

**Issue by BrandonKMLee** [platers/MAL-Map#15]
If you want to measure the significance of a node, centrality will be useful. See more at https://github.com/networkx/networkx/issues/4973
Generally this can be output as a Dictionary (Key-Value pairs) of nodes and scores.

For Node Roles, there are multiple ways to go about it (other than https://github.com/benedekrozemberczki/karateclub)
- RoleSim https://github.com/abhishekmaha23/RoleSim-Python
- ReFeX and RolX https://github.com/dkaslovsky/GraphRole
- AsCos, HITS, SimRank, TacSim https://github.com/caesar0301/graphsim
- AsCos, SimRank, RSS, LHN https://github.com/hhchen1105/networkx_addon
- SimRank, SimRank*, JacSim, and JPRank https://github.com/mrhhyu/EMB_vs_LB
- RWR, Personal PageRank https://github.com/jinhongjung/pyrwr
- Delta-SimRank https://github.com/amir-f/delta-simrank

Use cases:
- Making some of the more important nodes bigger for comparison
- Filtering some of the less relevant nodes for ease of viewing

**Comment by BasLaa** [comment]
I think that adding some of the algorithms you mentioned in [#4973](https://github.com/networkx/networkx/issues/4973) would be very useful. Especially since I've been coming across them in a university project. I believe Leverage Centrality was already implemented by someone a while ago, but the others were never actually done? If so, I'm gunna work on that this week.

**Comment by BrandonKMLee** [comment]
@BasLaa would you insist on a JS-based implementation? That would be exteremely useful!

**Comment by BasLaa** [comment]
@BrandonKMLee I'm confused, why a JavaScript based implementation? I just meant implementing the algorithms in Python in NetworkX.

**Comment by BrandonKMLee** [comment]
@BasLaa that is because ultimately this is a JS app, and moving data from NetworkX to MAL-Map (as a Python to JS issue) is still kind of fuzzy at the edges.

**Comment by BasLaa** [comment]
@BrandonKMLee I see that I haven't paid close attention. I came to this issue from some link on the NetworkX github page, not realising this was something different...
I have very little experience with JS, so I don't think I'm the right person for this job. 
I can implement them in Python in NetworkX though.
Sorry about that!

**Comment by BrandonKMLee** [comment]
@BasLaa thanks for wanting to help out with NetworkX centrality! This is always needed for more universal functions.

**Comment by platers** [comment]
I've now fully migrated to cdlib using the infomap algorithm. Infomap is the only one that worked at all for some reason. Anyway it works great, was getting inconsistent clusters before.
