### ISSUE TITLE
More data sources

### ISSUE THREAD

**Issue by platers** [platers/MAL-Map#2]
AnimePlanet: Might have higher quality data. Currently no API.
AniList: Has graphQL API, much more recs than MAL

**Comment by BrandonKMLee** [comment]
Taking a look at https://github.com/manami-project/anime-offline-database

**Comment by BrandonKMLee** [comment]
Also how is the aggregation, since for multi-layer networks can be useful fore Community Detection and Node Embedding?
https://github.com/platers/MAL-Map/issues/3 https://github.com/platers/MAL-Map/issues/15

**Comment by platers** [comment]
https://github.com/platers/MAL-Map/blob/dev/data-collection/recs.ts#L18

This is the function to create the edges. Each node contributes a total of 1 weight to its edges.
