### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by koenhagen** [platers/MAL-Map#35]
Hi, I love this tool you've built here. I went ahead and repurposed it with TMDb to get the same graph but with movies. So far everything went nicely and npm run dev works splendid. https://github.com/koenhagen/Movie-map

However I tried multiple hosting platforms and they all seem to struggle with the deployment part. I don't have any experience with deploying, so that might a the root of all these problems, but I was wondering how you deploy your website? I tried Amplify, Gitlab, Vercel, but no luck so far.

**Comment by platers** [comment]
Cool fork! I deploy right here on github pages. Its automated using a github action, see https://github.com/platers/MAL-Map/blob/master/.github/workflows/main.yml

`npm run build` should generate the source files in svelte/public which you can host anywhere. Its just a client side site, no server necessary.

**Comment by koenhagen** [comment]
I've figured it out! I did not have my base directory set right. I am sorry I had to bother you. Amazing work anyhow!
