### ISSUE TITLE
page not loading?

### ISSUE THREAD

**Issue by thijsi123** [platers/MAL-Map#7]
The page isn't loading correctly on chrome and brave, but it does on edge.
I reported it as broken site to brave though maybe they'll fix it.
![image](https://user-images.githubusercontent.com/64159148/149501999-7d4c1b99-b486-45dd-8a86-6aaa4a190910.png)

![image](https://user-images.githubusercontent.com/64159148/149502314-1acc37ad-71f4-41f3-8ab1-76b739d1f495.png)

**Comment by platers** [comment]
strange, it works on chrome for almost everyone

**Comment by thijsi123** [comment]
Weird...
I'll try my best to figure out what's wrong.

**Comment by thijsi123** [comment]
I had to enable Hardware acceleration.
Seems it's fixed now.

**Comment by thijsi123** [comment]
but now it's missing icons 😅
![image](https://user-images.githubusercontent.com/64159148/149619556-9ede9263-e9b3-4889-bf28-83f2410179d0.png)
