### ISSUE TITLE
Suggestion: Native Japanese and Romaji titles support

### ISSUE THREAD

**Issue by lvctr** [platers/MAL-Map#9]
I would love to share this with my friends, but no native Japanese support makes it hard as English titles are very different from the original titles. MAL does have native titles in its API, so this would technically be possible.

**Comment by alexmuch** [comment]
The Anilist API has the data for native and romaji titles. It also has references to the MAL IDs for each Anilist entry which should makes things easy to cross reference.

**Comment by platers** [comment]
MAL provides title, nativeTitle and englishTitle, is title good enough? Native title is hard because the font doesn't support it and I can't understand what I'm doing.

**Comment by platers** [comment]
https://www.malmap.net/#language=ja

Romaji titles now supported
